#!/usr/bin/env python3
"""Second pass: handle mixed chi-english patterns and remaining Chinese phrases."""
import re, sys, json

files = sys.argv[1:] if len(sys.argv) > 1 else [
    'pydme/actions/aiops.py', 'pydme/actions/backup.py', 'pydme/actions/fcswitch.py',
    'pydme/actions/ipswitch.py', 'pydme/actions/protect.py', 'pydme/actions/tenant.py',
    'pydme/actions/virt.py', 'pydme/actions/workflow.py', 'pydme/cli.py',
]

SUBSTITUTIONS = [
    # aiops.py - mixed chi-english (the worst file)
    ('告警', 'alarm'),
    ('查询', 'query'),
    ('创建', 'create'),
    ('删除', 'delete'),
    ('修改', 'modify'),
    ('任务', 'task'),
    ('确认', 'acknowledge'),
    ('取消确认', 'unacknowledge'),
    ('清除', 'clear'),
    ('信息', 'info'),
    ('列表', 'list'),
    ('参数', 'parameter'),
    ('类型', 'type'),
    ('状态', 'status'),
    ('名称', 'name'),
    ('描述', 'description'),
    ('数据', 'data'),
    ('结果', 'result'),
    ('链接', 'link'),
    ('下载', 'download'),
    ('文件', 'file'),
    ('收集', 'collect'),
    ('分析', 'analysis'),
    ('诊断', 'diagnosis'),
    ('时间', 'time'),
    ('开始', 'start'),
    ('结束', 'end'),
    ('当前', 'current'),
    ('历史', 'history'),
    ('总数', 'total'),
    ('详情', 'detail'),
    ('指标', 'indicator'),
    ('监控', 'monitor'),
    ('对象', 'object'),
    ('资源', 'resource'),
    ('策略', 'policy'),
    ('检查', 'check'),
    ('执行', 'execute'),
    ('启用', 'enable'),
    ('禁用', 'disable'),
    ('异常', 'abnormal'),
    ('健康', 'health'),
    ('性能', 'performance'),
    ('容量', 'capacity'),
    ('拓扑', 'topology'),
    ('图库', 'gallery'),
    ('磁盘', 'disk'),
    ('主机', 'host'),
    ('端口', 'port'),
    ('硬盘', 'hard disk'),
    ('控制器', 'controller'),
    ('节点', 'node'),
    ('级别', 'level'),
    ('紧急', 'critical'),
    ('重要', 'major'),
    ('次要', 'minor'),
    ('提示', 'info'),
    ('警告', 'warning'),
    ('成功', 'success'),
    ('失败', 'failed'),
    ('等待', 'waiting'),
    ('事件', 'event'),
    ('原因', 'reason'),
    ('条件', 'condition'),
    ('位置', 'location'),
    ('来源', 'source'),
    ('分类', 'category'),
    ('预置', 'pre-defined'),
    ('自定义', 'custom'),
    ('正序', 'ascending'),
    ('倒序', 'descending'),
    ('时分秒', 'HH:MM:SS'),
    ('年月日', 'YYYY-MM-DD'),
    ('分页', 'pagination'),
    ('页码', 'page number'),
    ('每页', 'per page'),
    ('偏移', 'offset'),
    ('排序', 'sort'),
    ('字段', 'field'),
    ('方向', 'direction'),
    ('过滤', 'filter'),
    ('精确', 'exact'),
    ('模糊', 'fuzzy'),
    ('默认', 'default'),
    ('必选', 'required'),
    ('必填', 'required'),
    ('可选', 'optional'),
    ('个字符', 'characters'),
    ('毫秒', 'milliseconds'),
    ('时间戳', 'timestamp'),
    ('最大值', 'max'),
    ('最小值', 'min'),
    ('平均值', 'average'),
    # protect specific
    ('双活', 'hypermetro'),
    ('保护组', 'protection group'),
    ('一致性组', 'consistency group'),
    ('本端', 'local'),
    ('远端', 'remote'),
    ('恢复', 'recovery'),
    ('同步', 'sync'),
    ('速率', 'speed'),
    ('阈值', 'threshold'),
    ('暂停', 'pause'),
    ('强制启动', 'force start'),
    ('切换', 'switch'),
    ('站点', 'site'),
    # cli
    ('风险', 'risk'),
    ('操作', 'operation'),
    ('警告', 'warning'),
    ('拒绝', 'refused'),
    ('环境变量', 'environment variable'),
    ('主题', 'topic'),
    ('动作', 'action'),
    ('子命令', 'subcommand'),
    ('必需', 'required'),
    ('使用方式', 'usage'),
    ('帮助', 'help'),
    ('运维', 'operations'),
    ('命令行', 'command line'),
    ('入口', 'entry'),
    # fcswitch specific
    ('光纤', 'fiber'),
    ('交换机', 'switch'),
    ('网络', 'network'),
    ('VSAN', 'VSAN'),
    ('控制处理器', 'controller'),
    # ipswitch specific
    ('机框', 'frame'),
    ('单板', 'board'),
    ('子卡', 'subcard'),
    ('电源', 'power supply'),
    ('风扇', 'fan'),
    # virt specific
    ('虚拟机', 'virtual machine'),
    ('集群', 'cluster'),
    ('数据存储', 'datastore'),
    # common remaining
    ('流水号', 'serial number'),
    ('步骤', 'step'),
    ('次数', 'count'),
    ('结果集', 'result set'),
    ('条数', 'count'),
    ('模型', 'model'),
    ('文档', 'document'),
    ('获取', 'get'),
    ('设置', 'set'),
    ('传入', 'pass'),
    ('返回', 'return'),
    ('属于', 'belongs to'),
    ('对应的', 'corresponding'),
    ('即', 'i.e.'),
    ('请', 'please'),
    ('使用', 'use'),
    ('查看', 'view'),
    ('运行', 'run'),
    ('了解', 'understand'),
    ('方式', 'method'),
    ('定义', 'definition'),
    ('方法', 'method'),
    ('通过', 'via'),
    ('从', 'from'),
    ('中', 'in'),
    ('为', 'as'),
    ('只', 'only'),
    ('如果', 'if'),
    ('提供', 'provide'),
    ('支持', 'support'),
    ('必须', 'must'),
    ('可以', 'can'),
    ('不能', 'cannot'),
    ('否', 'no'),
    ('是', 'yes'),
    ('和', 'and'),
    ('与', 'and'),
    ('或', 'or'),
    ('共', 'total'),
    ('内', 'within'),
    ('超', 'over'),
    ('已', 'already'),
    ('未', 'not'),
    ('无', 'no'),
    ('每', 'per'),
    ('第', ''),
    ('个', ''),
    ('的', ' '),
    ('有', 'has'),
    ('多', 'multiple'),
    ('少', 'few'),
    ('大', 'large'),
    ('小', 'small'),
    ('长', 'long'),
    ('短', 'short'),
    ('新', 'new'),
    ('旧', 'old'),
    ('会', 'will'),
    ('将', 'will'),
    ('可', 'can'),
    ('需', 'need'),
    ('能', 'can'),
    ('包括', 'include'),
    ('包含', 'contains'),
    ('以及', 'and'),
    ('等', 'etc.'),
    ('表示', 'indicates'),
    ('用于', 'for'),
    ('根据', 'according to'),
    ('之间', 'between'),
    ('范围', 'range'),
    ('格式', 'format'),
    ('规则', 'rule'),
    ('模式', 'mode'),
    ('策略', 'policy'),
    ('规则', 'rule'),
    ('方式', 'method'),
    ('数量', 'count'),
    ('容量', 'capacity'),
    ('大小', 'size'),
    ('长度', 'length'),
    ('宽度', 'width'),
    ('高度', 'height'),
    ('深度', 'depth'),
    ('时间', 'time'),
    ('日期', 'date'),
    ('编号', 'number'),
    ('序号', 'sequence'),
    ('标识', 'identifier'),
    ('标志', 'flag'),
    ('开关', 'switch'),
    ('选项', 'option'),
    ('值', 'value'),
    ('组', 'group'),
    ('集', 'set'),
    ('条', ''),
    ('项', 'item'),
    ('张', ''),
    ('个', ''),
]


def has_chinese(text):
    return bool(re.search(r'[\u4e00-\u9fff]', text))


def apply_subs(text):
    """Apply character/word substitutions preserving context."""
    # Apply long-to-short substitutions
    for cn, en in sorted(SUBSTITUTIONS, key=lambda x: -len(x[0])):
        text = text.replace(cn, en)
    return text


def main():
    total_remaining = 0
    for fpath in files:
        with open(fpath, 'r', encoding='utf-8') as f:
            content = f.read()
        
        before_count = len(re.findall(r'[\u4e00-\u9fff]', content))
        content = apply_subs(content)
        after_count = len(re.findall(r'[\u4e00-\u9fff]', content))
        
        with open(fpath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        rem_lines = sum(1 for line in content.split('\n') if has_chinese(line))
        total_remaining += rem_lines
        print(f"{fpath}: {before_count - after_count} chars removed, {rem_lines} lines with Chinese remaining")

    print(f"\nTotal remaining Chinese lines across all files: {total_remaining}")


if __name__ == '__main__':
    main()
